CC=gcc

main: main.c point.c listpos.c listdinpos.c matrix.c wordmachine.c charmachine.c queue.c stack.c
		gcc -o main main.c point.c listpos.c listdinpos.c matrix.c wordmachine.c charmachine.c queue.c stack.c